#!/usr/bin/env bash
# merge-prs.sh <pr-number>... — merge each PR's head into the current branch with the resolution policy:
#  generated files (index.json, CATALOG.md, research/INDEX.md) -> regenerated by build-index.py
#  research/ledger.jsonl -> union of both sides, dedup by .repo keeping the LAST occurrence (theirs after ours)
#  research/*.md add/add -> theirs (newer analysis)
#  anything else conflicting -> stop and report
set -uo pipefail
cd /home/luisliev/repos/claude-common || exit 1
GEN='index.json CATALOG.md research/INDEX.md'
dedupe_ledger() {
  python3 - "$@" <<'PY'
import sys, json
lines=[]
for p in sys.argv[1:]:
    with open(p) as f: lines += [l.rstrip('\n') for l in f if l.strip()]
last={}
for i,l in enumerate(lines):
    try: last[json.loads(l)['repo']]=i
    except Exception as e: print(f"bad ledger line: {l[:80]} ({e})", file=sys.stderr); sys.exit(1)
out=[l for i,l in enumerate(lines) if last[json.loads(l)['repo']]==i]
open('research/ledger.jsonl','w').write('\n'.join(out)+'\n')
print(f"ledger: {len(lines)} lines -> {len(out)} unique repos", file=sys.stderr)
PY
}
for n in "$@"; do
  br=$(gh pr view "$n" --json headRefName,title -q '.headRefName')
  title=$(gh pr view "$n" --json title -q .title)
  echo "=== PR #$n ($br): $title"
  if git merge --no-ff --no-commit -q "origin/$br" 2>/dev/null; then :; fi
  conflicts=$(git diff --name-only --diff-filter=U)
  other=""
  for f in $conflicts; do
    case "$f" in
      index.json|CATALOG.md|research/INDEX.md) git checkout -q --theirs -- "$f" 2>/dev/null || git show ":3:$f" > "$f"; git add "$f" ;;
      research/ledger.jsonl) git show ":2:$f" > /tmp/ours.jsonl; git show ":3:$f" > /tmp/theirs.jsonl; dedupe_ledger /tmp/ours.jsonl /tmp/theirs.jsonl || exit 1; git add "$f" ;;
      research/*.md) git checkout -q --theirs -- "$f"; git add "$f" ;;
      *) other="$other $f" ;;
    esac
  done
  if [ -n "$other" ]; then echo "!!! unresolved conflicts in PR #$n:$other"; git status --short | grep -E '^(UU|AA|DU|UD)' ; exit 2; fi
  # even a clean merge can leave duplicate ledger records (different positions): dedupe globally
  dedupe_ledger research/ledger.jsonl || exit 1
  python3 scripts/build-index.py >/dev/null || { echo "!!! build-index failed after PR #$n"; exit 3; }
  jq empty index.json && jq -c . research/ledger.jsonl >/dev/null || { echo "!!! invalid json after PR #$n"; exit 3; }
  git add -A
  git commit -q -m "Merge PR #$n: $title

Generated files regenerated by build-index.py; research ledger deduplicated (newest analysis wins).

Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>" || { echo "!!! commit failed for PR #$n"; exit 4; }
  echo "merged #$n -> $(git rev-parse --short HEAD); conflicts resolved: ${conflicts:-none}" | tr '\n' ' '; echo
done
